# Generated by Django 4.1.7 on 2023-02-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм ID юзера')),
                ('fullname', models.CharField(max_length=30, verbose_name='Имя и фамилия пользователя')),
                ('is_subscripted', models.BooleanField(default=False, verbose_name='Оплатил подписку')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм ID юзера')),
                ('fullname', models.CharField(max_length=30, verbose_name='Имя и фамилия пользователя')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'db_table': 'contractor',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('in_work', models.BooleanField(default=False, verbose_name='В работе')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.client', verbose_name='Клиент')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.contractor', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='api.task', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
    ]
