# Generated by Django 4.1.7 on 2023-02-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contractor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Подрядчик', 'verbose_name_plural': 'Подрядчики'},
        ),
    ]
